"""baseline current schema

This project ran without Alembic for a while (schema changes were applied
ad hoc -- see the old `ensure_series_state_columns()` in bootstrap.py). This
revision is the "adopt Alembic into an existing project" baseline: it's a
frozen snapshot of the `series`/`books` schema as of the point Alembic was
introduced, written explicitly (not delegated to live `models.Base.metadata`)
so later migrations stay meaningful as models.py continues to evolve.

  - Fresh databases: `alembic upgrade head` creates this schema from scratch.
  - The existing personal database already had this exact schema (patched
    up over time by the old ad-hoc migration code), so it was stamped at
    this revision with `alembic stamp head` instead of actually running it.

Revision ID: bf8439427a1e
Revises:
Create Date: 2026-07-13 10:25:12.069362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'bf8439427a1e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('tags', sqlite.JSON(), nullable=True),
    sa.Column('is_finished', sa.Boolean(), nullable=True),
    sa.Column('total_books', sa.Integer(), nullable=True),
    sa.Column('books_in_series', sqlite.JSON(), nullable=True),
    sa.Column('series_status', sa.String(), nullable=True),
    sa.Column('next_unread_book_number', sa.Float(), nullable=True),
    sa.Column('next_upcoming_book_number', sa.Float(), nullable=True),
    sa.Column('missing_books', sqlite.JSON(), nullable=True),
    sa.Column('last_checked', sa.Date(), nullable=True),
    sa.Column('has_new_books', sa.Boolean(), nullable=True),
    sa.Column('has_unread_books', sa.Boolean(), nullable=True),
    sa.Column('has_upcoming_books', sa.Boolean(), nullable=True),
    sa.Column('is_caught_up', sa.Boolean(), nullable=True),
    sa.Column('title_normalization_mode_override', sa.String(), nullable=True),
    sa.Column('goodreads_series_id', sa.String(), nullable=True),
    sa.Column('storygraph_series_id', sa.String(), nullable=True),
    sa.Column('import_source', sa.String(), nullable=True),
    sa.Column('import_raw_headers', sqlite.JSON(), nullable=True),
    sa.Column('import_raw_row', sqlite.JSON(), nullable=True),
    sa.Column('import_errors', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_series_id'), ['id'], unique=False)

    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('series_order', sa.Integer(), nullable=True),
    sa.Column('series_total_books', sa.Integer(), nullable=True),
    sa.Column('is_series_finished', sa.Boolean(), nullable=True),
    sa.Column('book_number', sa.Float(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('edition', sa.String(), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('isbn', sa.String(), nullable=True),
    sa.Column('isbn13', sa.String(), nullable=True),
    sa.Column('asin', sa.String(), nullable=True),
    sa.Column('google_books_id', sa.String(), nullable=True),
    sa.Column('goodreads_id', sa.String(), nullable=True),
    sa.Column('storygraph_id', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_date', sa.Date(), nullable=True),
    sa.Column('date_added', sa.Date(), nullable=True),
    sa.Column('date_started', sa.Date(), nullable=True),
    sa.Column('date_finished', sa.Date(), nullable=True),
    sa.Column('read_status', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('external_rating', sa.Float(), nullable=True),
    sa.Column('external_rating_count', sa.Integer(), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sqlite.JSON(), nullable=True),
    sa.Column('is_upcoming_auto', sa.Boolean(), nullable=True),
    sa.Column('is_upcoming_final', sa.Boolean(), nullable=True),
    sa.Column('is_missing', sa.Boolean(), nullable=True),
    sa.Column('record_status', sa.String(), nullable=True),
    sa.Column('import_source', sa.String(), nullable=True),
    sa.Column('import_raw_headers', sqlite.JSON(), nullable=True),
    sa.Column('import_raw_row', sqlite.JSON(), nullable=True),
    sa.Column('import_errors', sqlite.JSON(), nullable=True),
    sa.Column('auto_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_books_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_books_id'))

    op.drop_table('books')
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_series_id'))

    op.drop_table('series')
    # ### end Alembic commands ###
